<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0-preview.5</Version>
    <FileVersion>1.0.0.5</FileVersion>
    <Company>IPKeep</Company>
    <Product>IPKeep</Product>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
